version: '3.8'

networks:
  proxy:
    external: true

services:
  music-api:
    container_name: music-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - proxy
