name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Build the binary
        run: go build -o ./topmusicstreaming  # on change le chemin de sortie du binaire

      - name: Deploy to VPS
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          sudo apt-get install -y sshpass
          mkdir -p ~/.ssh/  # Création du répertoire .ssh si nécessaire
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          sshpass -p $SERVER_PASSWORD scp ./topmusicstreaming $SERVER_USER@$SERVER_IP:/root/topmusicstreaming  # on utilise scp pour copier le binaire
          sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart topmusicstreaming"
