name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Build the binary
        run: go build -o /root/topmusicstreaming

      - name: Deploy to VPS
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: 217.160.47.223
          SERVER_USER: root
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" /root/topmusicstreaming $SERVER_USER@$SERVER_IP:/root/topmusicstreaming
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "sudo systemctl restart topmusicstreaming"

